### ISSUE TITLE
在cockpit中配置网络的问题

### ISSUE THREAD

**Issue by LingjieJin** [kekylin/Debian-HomeNAS#5]
使用cockpit管理界面配置以太网（比如设置一个静态连接），需要先去/etc/NetworkManager目录下找到NetworkManager.conf文件，进行如下修改：
[ifupdown]
managed=false（改为true，表示使用NetworkManager去管理）
脚本的流程只注释掉了原先network的配置文件。
我这边按照这样修改就能在界面配置了。（如果界面成功配置，在/etc/NetworkManager/system-connections目录下会生成一个配置文件）

**Comment by kekylin** [comment]
感谢提醒！
